/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: MATH SQRT Example
*              for ModusToolbox. This example shows the calculation of square
*              root of a number using MATH CORDIC BLOCK of XMC.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "xmc_common.h"
#include "xmc_math.h"
#include "math.h"
#include "cybsp.h"
#include "cy_utils.h"
#include "retarget_io.h"
#include <stdio.h>
#include <string.h>

/*******************************************************************************
* Defines
*******************************************************************************/

/* Input number for which sqrt is calculated */
#define INPUT_NUM           (0.25F)

/* Size of the string buffer which stores float values */
#define STRING_BUF_SIZE     (32)

/* Convert Q15 number to float format */
__STATIC_INLINE float q15_to_float(int16_t a)
{ 
    return ( (float) a / 0x8000 );
}

/* Convert Q31 number to float format */
__STATIC_INLINE float q31_to_float(int32_t a)
{ 
    return ( (float) a / 0x80000000 );
}

/* Convert float to Q15 number */
__STATIC_INLINE int32_t float_to_q15(float a)
{ 
    return (int16_t)( (a * 0x8000) + 0.5F );
}

/* Convert float to Q31 number */
__STATIC_INLINE int32_t float_to_q31(float a)
{ 
    return (int32_t)( (a * 0x80000000) + 0.5F );
}

/*******************************************************************************
* Function Name: float_to_string
********************************************************************************
* Summary:
*  Function to convert a float number to a string
*
* Parameters:
*  char* string_buffer - Pointer to the string
*  uint8_t buf_size    - Size of the string buffer
*  float number        - Float number that needs to be converted to string
*
* Return:
*  void
*
*******************************************************************************/
void float_to_string(char* string_buffer, uint8_t buf_size, float number)
{
    /* Check if number is negative */
    uint8_t is_negative;
    if(number < 0)
    {
        is_negative = 1;
        number = -number;
    }
    else
    {
        is_negative = 0;
    }

    int integral_part = (int)number;
    int decimal_part = (number - integral_part) * 1000;
    if(is_negative)
    {
        snprintf(string_buffer, buf_size, "-%d.%03d", integral_part, decimal_part);
    }
    else
    {
        snprintf(string_buffer, buf_size, "%d.%03d", integral_part, decimal_part);
    }
}

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. It calculates the square root of the given input.
* The following operations are executed in this function:
*  1. Initialize the device and peripherals.
*  2. Convert the input number to Q31 format.
*  3. Calculate the square root using MATH-CORDIC block using the number
*     obtained in step 2 and print using UART.
*  4. Obtain the square root using software implemented function sqrtf() and
*     print using UART. 
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Variables Initialization */ 
    int32_t sqr_root_cordic_q31; 
    float sqr_root_cordic_float, sqr_root_software_float;
    char string_buff[STRING_BUF_SIZE];

    /* Initialize the device and board peripherals */
    result = cybsp_init() ;

    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize printf retarget */
    retarget_io_init();

    /* \x1b[2J\x1b[;H - ANSI ESC sequence to clear screen. */
    printf("\x1b[2J\x1b[;H");
    printf("===============================================================\r\n");
    printf("XMC MCU: MATH SQRT example\r\n");
    printf("===============================================================\r\n\n");
    
    /* Calculating Square root of the input using CORDIC block */
    sqr_root_cordic_q31 = XMC_MATH_CORDIC_Q31_Sqrt(float_to_q31( INPUT_NUM ));
   
    /* Print the result on the UART */
    printf("Sqr_root_CORDIC_Q31 = %ld \r\n", sqr_root_cordic_q31);
   
    /* Convert obtained Q31 square root value to float number */
    sqr_root_cordic_float = q31_to_float( sqr_root_cordic_q31 );
    float_to_string(string_buff, STRING_BUF_SIZE, sqr_root_cordic_float);

    /* Print the obtained square root on UART */
    printf("Sqr_root_CORDIC_float = %s\r\n", string_buff);

    /* Calculating Square root of the input using MATH.h function */
    sqr_root_software_float = sqrtf( INPUT_NUM );
    float_to_string(string_buff, STRING_BUF_SIZE, sqr_root_software_float);
   
    /* Print the obtained square root on UART */
    printf("Sqr_root_Software_float = %s\r\n", string_buff);

    while(1);
}

/* [] END OF FILE */
